### ISSUE TITLE
电子书的微软网盘链接都挂了

### ISSUE THREAD

**Issue by ikkyusan123** [programthink/books#11]
微软网盘链接挂了后，只剩下BT Sync同步软件了，我只想看某本书，但是它会把所有的都同步下来，选择性同步需要专业版才行。请更新微软网盘链接

**Comment by zhangchi0729** [comment]
> 重要：确保之前没有点击过“试用Pro”，如果正在试用中，请全新安装一遍（经群友实践，如果已经在试用Pro，使用下面的方法会导致试用立即到期，失败。
> 
> 把系统时间调到2020年；
> 打开 Sync 客户端，点击试用 Pro ，这时候会有各种红色警报时间错误，不用着急；
> 退出 Sync 客户端，并把系统时间调回来；
> 打开 Sync 开始使用，30天试用期到了之后，再次如法炮制即可
> 备注：
> 
> 不一定非要修改成2020，只要在当前日期之后都可；
> 以上办法已经在 Windows 和群晖上验证有效， Sycn 客户端均为最新版；
> Win 客户客户端重装办法：在资源管理器地址栏输入 %APPDATA% 找到 Resilio Sync 文件夹删掉就可以了；请注意删掉后原来的任务都不见了，需要重新添加（文件还在）；
> 有条件的话请支持正版，少吃一顿大餐，多下几部大片

syncfan上看到的方法你可以试试

**Comment by OOnnnOO** [comment]
移动版Sync，不是pro也可以进行选择性同步

**Comment by OOnnnOO** [comment]
另外，微软网盘的链接没有挂，刚刚试了，可以打开！

**Comment by ikkyusan123** [comment]
谢谢，我昨天打不开，刚才试了一下，确实可以打开了，博主把这个issue关了吧。

**Comment by johnhuo** [comment]
自己可以关了的。访问不了可能是因为你的网络问题

2017年2月28日 09:27，"ikkyusan123" <notifications@github.com>写道：
