### ISSUE TITLE
博客 EPUB 格式的排版问题

### ISSUE THREAD

**Issue by wizardforcel** [programthink/books#12]
博客的 EPUB 格式有侧栏，导致正文太窄，影响阅读。

另外建议每一年打一个包，增量更新。都打到一起每次下载也是个麻烦。

**Comment by programthink** [comment]
@wizardforcel 
关于显示问题
现在 epub 和 chm 格式的正文里面，已经是全屏显示，没有右边的侧栏。

关于打包的问题
如今采用 BTsync 进行自动同步，无需手工下载。
同步完成后，俺提供了自动生成电子书（epub & chm）的脚本，一键式生成。
