### ISSUE TITLE
微软网盘的分享失效了

### ISSUE THREAD

**Issue by MichaelSun1001** [programthink/books#130]
点击电子书的微软网盘链接后，什么都没有，失效了。

**Comment by Jamesqiu-123** [comment]
什么时候失效的

**Comment by luuthink** [comment]
他好像提到过这个问题，我用BTsync 也就是现在的 https://www.resilio.com/ ，还是很好用的，下载软件，输入他提供的key就可以了

**Comment by DesphySallau** [comment]
微软网盘有时候会失效，但有时候又可以...

**Comment by K10308** [comment]
这是来自QQ邮箱的假期自动回复邮件。你好，我最近正在休假中，无法亲自回复你的邮件。我将在假期结束后，尽快给你回复。

**Comment by MingDaoLX** [comment]
> 他好像提到过这个问题，我用BTsync 也就是现在的 https://www.resilio.com/ ，还是很好用的，下载软件，输入他提供的key就可以了

现在还能正常使用嘛，是不是pc端能用，安卓手机好像不行。

**Comment by K10308** [comment]
这是来自QQ邮箱的假期自动回复邮件。你好，我最近正在休假中，无法亲自回复你的邮件。我将在假期结束后，尽快给你回复。

**Comment by luuthink** [comment]
> > 他好像提到过这个问题，我用BTsync 也就是现在的 https://www.resilio.com/ ，还是很好用的，下载软件，输入他提供的key就可以了
> 
> 现在还能正常使用嘛，是不是pc端能用，安卓手机好像不行。

我没有用过手机端呢， 电脑端还能正常用，看官网上说 https://www.resilio.com/individuals/ ，手机端在google play里，应该也能用吧

**Comment by qoos-0221** [comment]
> 他好像提到过这个问题，我用BTsync 也就是现在的 https://www.resilio.com/ ，还是很好用的，下载软件，输入他提供的key就可以了He seems to have mentioned this problem, I use BTsync, which is now https://www.resilio.com/, and it's still very easy to use, download the software, enter the key he provided, and it's OK

为什么我的BT同步不出来书啊，我刚看了扫盲，不是太懂，下载的BT是最新版的

**Comment by K10308** [comment]
这是来自QQ邮箱的假期自动回复邮件。你好，我最近正在休假中，无法亲自回复你的邮件。我将在假期结束后，尽快给你回复。

**Comment by K10308** [comment]
这是来自QQ邮箱的假期自动回复邮件。你好，我最近正在休假中，无法亲自回复你的邮件。我将在假期结束后，尽快给你回复。
