### ISSUE TITLE
预测一下博主这种做法会加速githu被墙

### ISSUE THREAD

**Issue by ibufu** [programthink/books#3]
但是我非常支持博主的做法和github被墙

**Comment by XL2014** [comment]
预测博文:Github与GFW的PK《第三季》

**Comment by chengzhoukun** [comment]
同样支持

**Comment by programthink** [comment]
多谢几位的支持 :)
感觉俺的影响力还没有这么大，暂时还不会引发《第三季》。

**Comment by Chenyao168** [comment]
我代表V2EX上的各路反华爱共的程序员，对编程随想等反动分子的无耻下流的返共行为表示严正抗议！

**Comment by Honghe** [comment]
博主何必为难github，又为难我们技术人员呢，这些言论可以自己建博客。现在github速度已经被限制挺多的了。

**Comment by xmdhs** [comment]
没事的
