### ISSUE TITLE
Onedrive提示：This item might not exist or is no longer available

### ISSUE THREAD

**Issue by kigawas** [programthink/books#30]

**Comment by liushengzu** [comment]
why？i like this contents very much!

**Comment by XavierXia** [comment]
onedrive不可用了
![image](https://user-images.githubusercontent.com/6349081/45477968-72360680-b775-11e8-9643-64b98270f79e.png)

**Comment by JeremiahZhang** [comment]
You can use BTsync just like the Blogger said.

**Comment by JeremiahZhang** [comment]
This issue can be closed. Thanks.
