### ISSUE TITLE
建议开源《太子党关系网络》这本书的Graphviz源代码

### ISSUE THREAD

**Issue by LinusSong** [programthink/books#4]
PDF版既无法编辑，又难以浏览，而且改用BT Sync之后，需要和庞大的政治类文件夹进行同步才能下载，更不必谈传播效果了。
Github的Fork和pull request功能有目共睹，开源Graphviz源代码，一是为了协作编辑，二是为了让人改编为Web版本，博主你这本书如果做成Web版的话，效果一定会比现在好太多了。
《太子党关系网络》是这份书单里面唯一一本博主自己写的书，还希望不要埋没了，开源出来吧

**Comment by programthink** [comment]
@LinusSong 
多谢提建议 :)

俺当初把资料从 Google Code 迁移到 GitHub，也是想借助 GitHub 的多人协作。
前面几个月比较忙（一个是迁移到 GitHub，一个是 Blogspot 全站支持 HTTPS 加密），都没来得及做这个事情。

接下来的计划是：
先在 GitHub 上建立一个 Faq 项目（目前已经有项目，但是内容还没写）
等 Faq 项目做完，再来搞这个《太子党关系网络》。
这个《太子党关系网络》，不光是开源，还会单独做成一个项目。
俺会把 Graphviz 拆分成多个文件，以利于多人协作。
敬请期待 :)

**Comment by zhuozhuo** [comment]
兄弟，太子党关系网络工程，已经被关闭了。有在其他Git上的下载地址么，或者可以发我邮箱一份么414816566@qq.com

**Comment by notlsd** [comment]
@zhuozhuo 竟然敢用 QQ 邮箱 ......

**Comment by zhuozhuo** [comment]
@notlsd 看下是没问题的，如果天朝想搞你，换什么都没用。不过你倒是提醒了我，估计这兄弟看到QQ邮箱不想发我了。换个gmail

**Comment by BobAlbert100** [comment]
好像很隐秘的样子。

**Comment by programthink** [comment]
@zhuozhuo 
《太子党关系网络》这个项目，并没有被关闭，只是因为 GitHub 收到中国官方的删除令，然后把这个项目设置为：对来自大陆地区的访问者不可见。

只需翻墙就可以正常浏览和下载。
[https://github.com/programthink/zhao](https://github.com/programthink/zhao)
