### ISSUE TITLE
希望作者能充满阳光, 这个时代够好的, 没有你想的那么黑暗.

### ISSUE THREAD

**Issue by AlienFromStar** [programthink/books#54]
如果你心中没有阳光，就算周围一片光明，你也会感到灰暗；如果你心中充满阳光，就是在黑暗中，也能看到希望。

**Comment by freedomandcourage** [comment]
呵呵～ 正是因为作者这样的人存在，才让这个时代显得没有那么黑暗，正是由于你这种人的存在，才让这个时代变得无比黑暗，揭露黑暗的是阳光～赞美黑暗的是恶魔～

**Comment by AlienFromStar** [comment]
你如何认定赞美黑暗呢,  先入为主的这套吵架方式我见的多了,  每个人的生活方式不同, 接受争议, 你有你的, 我可以我的, 只是相比花大量时间整理这些所谓的黑暗, 我觉得努力提高自己, 让自己变得更有竞争力, 让自己去适应这个社会要实在的多, 作者花的时间挺多的吧, 何不好好工作, 陪陪家人, 至少你所认为的黑暗我还没接触到, 话又说回来, 难道你是何方圣人, 能洞悉我们不知道的一切, 你所说的真相就是真相吗?  一个对国家对民族有偏见的人是没有权利去评判的.

**Comment by ijkzen** [comment]
打起来，打起来

**Comment by freedomandcourage** [comment]
哦，你这种人，生在朝鲜也会这么说的！你也会极其适应朝鲜的体制～你可以选择自己闷起头来告诉自己岁月静好啊！作者和你不是一个层次的人，你是不会理解的！
就像太监告诉我们，你看我不也过来了嘛？为什么就你们不能忍受呢？

**Comment by AlienFromStar** [comment]
你这个比喻很不恰当的, 你为什么要告诉我们作为太监的你是正常的呢? 既然你愿意自宫成为你想象中的"正常人", 那就准你了.

**Comment by ijkzen** [comment]
不能打架! 金坷垃好处都有啥? 谁说对了就给他

**Comment by AlienFromStar** [comment]
不是吵架, 这是互相交流, 就此打住了, 开始工作了.

**Comment by wizardforcel** [comment]
有光的地方就有阴影，只不过我们选择把它揭发出来，你选择视而不见。
