### ISSUE TITLE
《经济学原理：宏观分册》第六版。以及推荐《哥德尔、艾舍尔、巴赫》

### ISSUE THREAD

**Issue by 0neSe7en** [programthink/books#7]
[哥德尔、艾舍尔、巴赫](http://1drv.ms/1nvKM5M)
[《经济学原理：宏观分册》第六版](http://1drv.ms/1nVBP6e)

**Comment by wocao1314** [comment]
123

**Comment by programthink** [comment]
@0neSe7en 
很抱歉这么久才回复你 :(
非常感谢你的分享！
下一次分享电子书的时候，俺把你推荐的这两本上传到网盘。
