### ISSUE TITLE
一些IT方面的书籍

### ISSUE THREAD

**Issue by BennyThink** [programthink/books#8]
# 已经在书单里搜索过了，都是没有的。

《图解密码技术》(日)结城浩，这本书暂时没找到pdf
<a href="http://7xool0.com1.z0.glb.clouddn.com/C++.Primer.Plus.pdf">C++ Primer Plus</a>  (美)史蒂芬 普拉达
<a href="http://7xool0.com1.z0.glb.clouddn.com/Python%E5%9F%BA%E7%A1%80%E6%95%99%E7%A8%8B(%E7%AC%AC2%E7%89%88).pdf">Python基础教程</a>  (挪威)赫特兰
<a href="http://7xool0.com1.z0.glb.clouddn.com/Linux%E5%91%BD%E4%BB%A4%E8%A1%8C.pdf">Linux命令行与Shell脚本编程大全</a>  (美)理查德·布鲁姆
<a href="http://7xool0.com1.z0.glb.clouddn.com/Thinking.in.C++.pdf">C++编程思想</a>     (美)布鲁斯·埃克尔
# 

docker类的书籍，也应该略作补充吧！

**Comment by BennyThink** [comment]
@programthink 
好久之前的issue！
等我假期整理下，直接来个PR吧，也省事😄

**Comment by mhxy13867806343** [comment]
来看看
